# Generated by Django 6.0.3 on 2026-04-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='contentApp__publish_3b1a2f_idx',
            old_name='contentApp__publish_c6c316_idx',
        ),
    ]
